# Lab 3: Pandas & Data Preprocessing

In [1]:
import pandas as pd

In [2]:
ecommerce_data = {
'OrderID': [101, 102, 103, 104, 105, 106, 107],
'CustomerName': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace'],
'Category': ['Electronics', 'Fashion', 'Electronics', 'Home', 'Fashion', 'Electronics', 'Home'],
'Amount': [200, 150, 300, 400, 250, 500, 350],
'Discount': [20, 10, 30, 50, 20, 60, 40],
'PurchaseDate': pd.to_datetime(['2023-11-20', '2023-11-21', '2023-11-22',
'2023-11-23', '2023-11-24', '2023-11-25', '2023-11-26']),
'City': ['New York', 'Los Angeles', 'New York', 'Chicago', 'Los Angeles', 'Chicago','New York']
}

data = [
{"id": 1, "age": 25, "income": 50000, "city": "New York", "purchased": "yes"},
{"id": 2, "age": 30, "income": 60000, "city": "San Francisco", "purchased": "no"},
{"id": 3, "age": None, "income": 75000, "city": "New York", "purchased": None},
{"id": 4, "age": 22, "income": None, "city": "Los Angeles", "purchased": "yes"},
{"id": 5, "age": 35, "income": 80000, "city": None, "purchased": "no"},
{"id": 6, "age": 29, "income": 58000, "city": "San Francisco", "purchased": "yes"},
{"id": 7, "age": None, "income": None, "city": "New York", "purchased": "no"},
{"id": 8, "age": 40, "income": 90000, "city": "San Francisco", "purchased": "yes"},
{"id": 9, "age": 28, "income": 65000, "city": "Los Angeles", "purchased": None},
{"id": 10, "age": 33, "income": 72000, "city": "New York", "purchased": "no"},
{"id": 11, "age": None, "income": 50000, "city": "Los Angeles", "purchased": "yes"},
{"id": 12, "age": 26, "income": 61000, "city": None, "purchased": "yes"},
{"id": 13, "age": 45, "income": 95000, "city": "San Francisco", "purchased": None},
{"id": 14, "age": 50, "income": None, "city": "Los Angeles", "purchased": "no"},
{"id": 15, "age": 38, "income": 70000, "city": "New York", "purchased": "yes"},
]

# Question 1

In [3]:
# Create the df from the given data: dict
df = pd.DataFrame(ecommerce_data)

1. What is the shape of the dataset?

In [4]:
print(f"Shape of given data: {df.shape}")
print(df.columns)

Shape of given data: (7, 7)
Index(['OrderID', 'CustomerName', 'Category', 'Amount', 'Discount',
       'PurchaseDate', 'City'],
      dtype='str')

In [5]:
print(df.head())

   OrderID CustomerName     Category  Amount  Discount PurchaseDate  \
0      101        Alice  Electronics     200        20   2023-11-20
1      102          Bob      Fashion     150        10   2023-11-21
2      103      Charlie  Electronics     300        30   2023-11-22
3      104        David         Home     400        50   2023-11-23
4      105          Eve      Fashion     250        20   2023-11-24

          City
0     New York
1  Los Angeles
2     New York
3      Chicago
4  Los Angeles

2. Are there any null values in the dataset?

In [6]:
print("Null values in dataset: ")
print(df.isna().sum())

Null values in dataset:
OrderID         0
CustomerName    0
Category        0
Amount          0
Discount        0
PurchaseDate    0
City            0
dtype: int64

3.Retrieve [Charlie Electronics 300] using loc and iloc

In [7]:
#using iloc
data_1 = df.iloc[2,[1,2,3]]
data_2 = df.loc[2, ["CustomerName", "Category", "Amount"]]
print("Retrieved using iloc: ")
print(data_1)
print("\nRetrieved using loc: ")
print(data_2)
#print(data.to_dict().values())

Retrieved using iloc:
CustomerName        Charlie
Category        Electronics
Amount                  300
Name: 2, dtype: object

Retrieved using loc:
CustomerName        Charlie
Category        Electronics
Amount                  300
Name: 2, dtype: object

4. Fetch rows for orders placed by customers from New York.

In [8]:
q_filter = df["City"] == "New York"
result = df[q_filter]
print(result)

   OrderID CustomerName     Category  Amount  Discount PurchaseDate      City
0      101        Alice  Electronics     200        20   2023-11-20  New York
2      103      Charlie  Electronics     300        30   2023-11-22  New York
6      107        Grace         Home     350        40   2023-11-26  New York

5. What is the average order amount? What is the total discount provided?

In [9]:
avg_order_amt = df["Amount"].mean()
total_discount = df["Discount"].sum()
print(f"Average order amount: {avg_order_amt:.2f}")
print(f"Total discount provided: {total_discount}")

Average order amount: 307.14
Total discount provided: 230

6. Sort the orders by Amount in descending order

In [10]:
df.sort_values(by="Amount", ascending=False)

,OrderID,CustomerName,Category,Amount,Discount,PurchaseDate,City
5,106,Frank,Electronics,500,60,2023-11-25,Chicago
3,104,David,Home,400,50,2023-11-23,Chicago
6,107,Grace,Home,350,40,2023-11-26,New York
2,103,Charlie,Electronics,300,30,2023-11-22,New York
4,105,Eve,Fashion,250,20,2023-11-24,Los Angeles
0,101,Alice,Electronics,200,20,2023-11-20,New York
1,102,Bob,Fashion,150,10,2023-11-21,Los Angeles

7. Display all orders where the Category is "Electronics" and the Amount is greater than 250.

In [106]:
q_filter = (df["Category"] == "Electronics") & (df["Amount"] > 250)
df[q_filter]

   OrderID CustomerName     Category  Amount  Discount PurchaseDate      City
2      103      Charlie  Electronics     300        30   2023-11-22  New York
5      106        Frank  Electronics     500        60   2023-11-25   Chicago

## Question 2

In [107]:
#exploring dataset
data_df = pd.DataFrame(data)
print(f"Shape: {data_df.shape}")
data_df.head()

Shape: (15, 5)

   id   age   income           city purchased
0   1  25.0  50000.0       New York       yes
1   2  30.0  60000.0  San Francisco        no
2   3   NaN  75000.0       New York       NaN
3   4  22.0      NaN    Los Angeles       yes
4   5  35.0  80000.0            NaN        no

In [108]:
data_df.isna().sum()

id           0
age          3
income       3
city         2
purchased    3
dtype: int64

1. Replace None in numerical fields (age, income) with mean/median.

In [109]:
# imputing null values
age_mean = data_df["age"].mean()
income_mean = data_df["income"].mean()
fill_values = {"age": age_mean, "income": income_mean}
data_df = data_df.fillna(value=fill_values)
print(data_df)

    id        age        income           city purchased
0    1  25.000000  50000.000000       New York       yes
1    2  30.000000  60000.000000  San Francisco        no
2    3  33.416667  75000.000000       New York       NaN
3    4  22.000000  68833.333333    Los Angeles       yes
4    5  35.000000  80000.000000            NaN        no
5    6  29.000000  58000.000000  San Francisco       yes
6    7  33.416667  68833.333333       New York        no
7    8  40.000000  90000.000000  San Francisco       yes
8    9  28.000000  65000.000000    Los Angeles       NaN
9   10  33.000000  72000.000000       New York        no
10  11  33.416667  50000.000000    Los Angeles       yes
11  12  26.000000  61000.000000            NaN       yes
12  13  45.000000  95000.000000  San Francisco       NaN
13  14  50.000000  68833.333333    Los Angeles        no
14  15  38.000000  70000.000000       New York       yes

2. Replace None in categorical fields (city, purchased) with mode or a placeholder
like "unknown".

In [110]:
fill_values_cat = data_df[["city", "purchased"]].mode().iloc[0].to_dict()
data_df = data_df.fillna(value=fill_values_cat)
print(data_df)

    id        age        income           city purchased
0    1  25.000000  50000.000000       New York       yes
1    2  30.000000  60000.000000  San Francisco        no
2    3  33.416667  75000.000000       New York       yes
3    4  22.000000  68833.333333    Los Angeles       yes
4    5  35.000000  80000.000000       New York        no
5    6  29.000000  58000.000000  San Francisco       yes
6    7  33.416667  68833.333333       New York        no
7    8  40.000000  90000.000000  San Francisco       yes
8    9  28.000000  65000.000000    Los Angeles       yes
9   10  33.000000  72000.000000       New York        no
10  11  33.416667  50000.000000    Los Angeles       yes
11  12  26.000000  61000.000000       New York       yes
12  13  45.000000  95000.000000  San Francisco       yes
13  14  50.000000  68833.333333    Los Angeles        no
14  15  38.000000  70000.000000       New York       yes

3. Normalize numerical fields (age, income) to a scale of 0-1 using min-max scaling
or standardization (z-score).

In [111]:
#zscore
data_df[["age", "income"]] = (
    (data_df[["age", "income"]] - data_df[["age", "income"]].mean())
    / data_df[["age", "income"]].std()
    ).round(3)
print(data_df)

    id    age  income           city purchased
0    1 -1.118  -1.473       New York       yes
1    2 -0.454  -0.691  San Francisco        no
2    3  0.000   0.482       New York       yes
3    4 -1.517   0.000    Los Angeles       yes
4    5  0.210   0.874       New York        no
5    6 -0.587  -0.847  San Francisco       yes
6    7  0.000   0.000       New York        no
7    8  0.875   1.656  San Francisco       yes
8    9 -0.720  -0.300    Los Angeles       yes
9   10 -0.055   0.248       New York        no
10  11  0.000  -1.473    Los Angeles       yes
11  12 -0.986  -0.613       New York       yes
12  13  1.539   2.047  San Francisco       yes
13  14  2.204   0.000    Los Angeles        no
14  15  0.609   0.091       New York       yes

4. Use one-hot encoding for the city

In [112]:
encoded_data_df = pd.get_dummies(data_df, columns=["city"], dtype=int)
print(encoded_data_df)

    id    age  income purchased  city_Los Angeles  city_New York  \
0    1 -1.118  -1.473       yes                 0              1
1    2 -0.454  -0.691        no                 0              0
2    3  0.000   0.482       yes                 0              1
3    4 -1.517   0.000       yes                 1              0
4    5  0.210   0.874        no                 0              1
5    6 -0.587  -0.847       yes                 0              0
6    7  0.000   0.000        no                 0              1
7    8  0.875   1.656       yes                 0              0
8    9 -0.720  -0.300       yes                 1              0
9   10 -0.055   0.248        no                 0              1
10  11  0.000  -1.473       yes                 1              0
11  12 -0.986  -0.613       yes                 0              1
12  13  1.539   2.047       yes                 0              0
13  14  2.204   0.000        no                 1              0
14  15  0.609   0.091       yes                 0              1

    city_San Francisco
0                    0
1                    1
2                    0
3                    0
4                    0
5                    1
6                    0
7                    1
8                    0
9                    0
10                   0
11                   0
12                   1
13                   0
14                   0

5. Use label encoding (e.g., yes=1, no=0) for purchase.

In [95]:
data_df["purchased"] = data_df["purchased"].map({"no": 0, "yes": 1})
print(data_df)

    id    age  income           city  purchased
0    1 -1.521  -1.521       New York          1
1    2 -0.093  -0.093  San Francisco          0
2    3 -0.093  -0.093       New York          1
3    4 -1.521  -0.093    Los Angeles          1
4    5 -0.093  -0.093       New York          0
5    6 -0.093  -0.093  San Francisco          1
6    7 -0.093  -0.093       New York          0
7    8 -0.093   1.325  San Francisco          1
8    9 -0.093  -0.093    Los Angeles          1
9   10 -0.093  -0.093       New York          0
10  11 -0.093  -1.521    Los Angeles          1
11  12 -0.093  -0.093       New York          1
12  13  1.325   2.743  San Francisco          1
13  14  2.743  -0.093    Los Angeles          0
14  15 -0.093  -0.093       New York          1